# permissions for end users to edit podwatchers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator-example
    app.kubernetes.io/managed-by: kustomize
  name: podwatcher-editor-role
rules:
- apiGroups:
  - core.example.com
  resources:
  - podwatchers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.example.com
  resources:
  - podwatchers/status
  verbs:
  - get
